const std = @import("std");

pub const Chip = enum {
    rp2040,
    rp2350,
};

pub const CpuArch = enum {
    arm,
    riscv,
};

pub fn build(b: *std.Build) void {
    const chip = b.option(Chip, "chip", "Target chip (rp2040 or rp2350)") orelse .rp2040;
    const cpu_arch = b.option(CpuArch, "cpu_arch", "CPU architecture (arm or riscv, rp2350 only)") orelse .arm;
    const board = b.option([]const u8, "board", "Target board (e.g., pico, pico_w, pico2)") orelse switch (chip) {
        .rp2040 => "pico",
        .rp2350 => "pico2",
    };

    const target_query = getTarget(chip, cpu_arch);
    const target = b.resolveTargetQuery(target_query);
    const optimize = b.standardOptimizeOption(.{});

    // Generate required config headers
    const generated = generateConfigHeaders(b, chip, board);

    // Install headers for downstream use
    b.getInstallStep().dependOn(&b.addInstallDirectory(.{
        .source_dir = generated,
        .install_dir = .header,
        .install_subdir = "",
    }).step);

    // Install SDK source headers
    installSdkHeaders(b);

    // Create an example/test library to verify the build works
    const example_lib = createExampleLibrary(b, target, optimize, chip, board, generated);
    b.installArtifact(example_lib);
}

fn generateConfigHeaders(b: *std.Build, chip: Chip, board: []const u8) std.Build.LazyPath {
    const wf = b.addWriteFiles();

    // Generate pico/version.h
    _ = wf.add("pico/version.h",
        \\/*
        \\ * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
        \\ *
        \\ * SPDX-License-Identifier: BSD-3-Clause
        \\ */
        \\
        \\// THIS FILE IS AUTOGENERATED; DO NOT EDIT
        \\
        \\#ifndef _PICO_VERSION_H
        \\#define _PICO_VERSION_H
        \\
        \\#define PICO_SDK_VERSION_MAJOR    2
        \\#define PICO_SDK_VERSION_MINOR    2
        \\#define PICO_SDK_VERSION_REVISION 0
        \\#define PICO_SDK_VERSION_STRING   "2.2.0"
        \\
        \\#endif
        \\
    );

    // Generate pico_config_extra_headers.h (empty by default)
    _ = wf.add("pico_config_extra_headers.h",
        \\// Extra headers - add custom includes here if needed
        \\
    );

    // Generate pico_config_platform_headers.h based on board and chip
    const platform_header = switch (chip) {
        .rp2040 => b.fmt(
            \\// Platform headers for RP2040
            \\#include "cmsis/rename_exceptions.h"
            \\#include "boards/{s}.h"
            \\
        , .{board}),
        .rp2350 => b.fmt(
            \\// Platform headers for RP2350
            \\#include "cmsis/rename_exceptions.h"
            \\#include "boards/{s}.h"
            \\
        , .{board}),
    };
    _ = wf.add("pico_config_platform_headers.h", platform_header);

    // Generate pico/config_autogen.h
    _ = wf.add("pico/config_autogen.h",
        \\// AUTOGENERATED - DO NOT EDIT
        \\//
        \\// This header includes platform and extra configuration headers.
        \\
        \\// Extra headers (custom user configuration)
        \\#include "pico_config_extra_headers.h"
        \\
        \\// Platform-specific headers (board and chip configuration)
        \\#include "pico_config_platform_headers.h"
        \\
    );

    return wf.getDirectory();
}

fn installSdkHeaders(b: *std.Build) void {
    // Install common headers
    const common_header_dirs = [_][]const u8{
        "src/common/pico_base_headers/include",
        "src/common/pico_binary_info/include",
        "src/common/pico_bit_ops_headers/include",
        "src/common/pico_divider_headers/include",
        "src/common/pico_sync/include",
        "src/common/pico_time/include",
        "src/common/pico_util/include",
        "src/common/pico_stdlib_headers/include",
        "src/common/hardware_claim/include",
        "src/boards/include",
    };

    for (common_header_dirs) |dir| {
        b.getInstallStep().dependOn(&b.addInstallDirectory(.{
            .source_dir = b.path(dir),
            .install_dir = .header,
            .install_subdir = "",
        }).step);
    }
}

fn createExampleLibrary(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    chip: Chip,
    board: []const u8,
    generated: std.Build.LazyPath,
) *std.Build.Step.Compile {
    // Create a minimal stub source file for the library
    const stub_wf = b.addWriteFiles();
    const stub_source = stub_wf.add("pico_sdk_stub.c",
        \\// Minimal stub to create a valid library artifact
        \\// Real SDK functionality comes from linking individual source files
        \\
        \\#include "pico/version.h"
        \\
        \\const int pico_sdk_version_major = PICO_SDK_VERSION_MAJOR;
        \\const int pico_sdk_version_minor = PICO_SDK_VERSION_MINOR;
        \\const int pico_sdk_version_revision = PICO_SDK_VERSION_REVISION;
        \\
    );

    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = false,
    });

    const lib = b.addLibrary(.{
        .linkage = .static,
        .name = "pico_sdk",
        .root_module = mod,
    });

    // Add generated include path first
    lib.addIncludePath(generated);

    // Add stub source
    lib.addCSourceFile(.{
        .file = stub_source,
        .flags = &.{},
    });

    // Add compile definitions
    addCompileDefinitions(lib, chip, board);

    return lib;
}

fn addIncludePaths(lib: *std.Build.Step.Compile, chip: Chip) void {
    const b = lib.step.owner;

    // Common include paths
    lib.addSystemIncludePath(b.path("src/common/pico_base_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_binary_info/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_bit_ops_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_divider_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_sync/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_time/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_util/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_stdlib_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/pico_usb_reset_interface_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/hardware_claim/include"));
    lib.addSystemIncludePath(b.path("src/common/boot_picobin_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/boot_picoboot_headers/include"));
    lib.addSystemIncludePath(b.path("src/common/boot_uf2_headers/include"));

    // Boards
    lib.addSystemIncludePath(b.path("src/boards/include"));

    // Chip-specific include paths
    switch (chip) {
        .rp2040 => {
            lib.addSystemIncludePath(b.path("src/rp2040/hardware_regs/include"));
            lib.addSystemIncludePath(b.path("src/rp2040/hardware_structs/include"));
            lib.addSystemIncludePath(b.path("src/rp2040/pico_platform/include"));
            lib.addSystemIncludePath(b.path("src/rp2040/boot_stage2/include"));
            lib.addSystemIncludePath(b.path("src/rp2_common/cmsis/stub/CMSIS/Device/RP2040/Include"));
        },
        .rp2350 => {
            lib.addSystemIncludePath(b.path("src/rp2350/hardware_regs/include"));
            lib.addSystemIncludePath(b.path("src/rp2350/hardware_structs/include"));
            lib.addSystemIncludePath(b.path("src/rp2350/pico_platform/include"));
            lib.addSystemIncludePath(b.path("src/rp2350/boot_stage2/include"));
            lib.addSystemIncludePath(b.path("src/rp2_common/cmsis/stub/CMSIS/Device/RP2350/Include"));
        },
    }

    // RP2 common include paths
    const rp2_common_include_dirs = [_][]const u8{
        "src/rp2_common/boot_bootrom_headers/include",
        "src/rp2_common/cmsis/include",
        "src/rp2_common/cmsis/stub/CMSIS/Core/Include",
        "src/rp2_common/hardware_adc/include",
        "src/rp2_common/hardware_base/include",
        "src/rp2_common/hardware_boot_lock/include",
        "src/rp2_common/hardware_clocks/include",
        "src/rp2_common/hardware_dcp/include",
        "src/rp2_common/hardware_divider/include",
        "src/rp2_common/hardware_dma/include",
        "src/rp2_common/hardware_exception/include",
        "src/rp2_common/hardware_flash/include",
        "src/rp2_common/hardware_gpio/include",
        "src/rp2_common/hardware_hazard3/include",
        "src/rp2_common/hardware_i2c/include",
        "src/rp2_common/hardware_interp/include",
        "src/rp2_common/hardware_irq/include",
        "src/rp2_common/hardware_pio/include",
        "src/rp2_common/hardware_pll/include",
        "src/rp2_common/hardware_powman/include",
        "src/rp2_common/hardware_pwm/include",
        "src/rp2_common/hardware_rcp/include",
        "src/rp2_common/hardware_resets/include",
        "src/rp2_common/hardware_riscv/include",
        "src/rp2_common/hardware_riscv_platform_timer/include",
        "src/rp2_common/hardware_rtc/include",
        "src/rp2_common/hardware_sha256/include",
        "src/rp2_common/hardware_spi/include",
        "src/rp2_common/hardware_sync/include",
        "src/rp2_common/hardware_sync_spin_lock/include",
        "src/rp2_common/hardware_ticks/include",
        "src/rp2_common/hardware_timer/include",
        "src/rp2_common/hardware_uart/include",
        "src/rp2_common/hardware_vreg/include",
        "src/rp2_common/hardware_watchdog/include",
        "src/rp2_common/hardware_xip_cache/include",
        "src/rp2_common/hardware_xosc/include",
        "src/rp2_common/pico_aon_timer/include",
        "src/rp2_common/pico_async_context/include",
        "src/rp2_common/pico_atomic/include",
        "src/rp2_common/pico_bit_ops/include",
        "src/rp2_common/pico_bootrom/include",
        "src/rp2_common/pico_bootsel_via_double_reset/include",
        "src/rp2_common/pico_clib_interface/include",
        "src/rp2_common/pico_crt0/include",
        "src/rp2_common/pico_cxx_options/include",
        "src/rp2_common/pico_divider/include",
        "src/rp2_common/pico_double/include",
        "src/rp2_common/pico_fix/rp2040_usb_device_enumeration/include",
        "src/rp2_common/pico_flash/include",
        "src/rp2_common/pico_float/include",
        "src/rp2_common/pico_i2c_slave/include",
        "src/rp2_common/pico_int64_ops/include",
        "src/rp2_common/pico_malloc/include",
        "src/rp2_common/pico_mem_ops/include",
        "src/rp2_common/pico_multicore/include",
        "src/rp2_common/pico_platform_common/include",
        "src/rp2_common/pico_platform_compiler/include",
        "src/rp2_common/pico_platform_panic/include",
        "src/rp2_common/pico_platform_sections/include",
        "src/rp2_common/pico_printf/include",
        "src/rp2_common/pico_rand/include",
        "src/rp2_common/pico_runtime/include",
        "src/rp2_common/pico_runtime_init/include",
        "src/rp2_common/pico_sha256/include",
        "src/rp2_common/pico_standard_binary_info/include",
        "src/rp2_common/pico_standard_link/include",
        "src/rp2_common/pico_status_led/include",
        "src/rp2_common/pico_stdio/include",
        "src/rp2_common/pico_stdio_semihosting/include",
        "src/rp2_common/pico_stdio_uart/include",
        "src/rp2_common/pico_stdio_usb/include",
        "src/rp2_common/pico_stdlib/include",
        "src/rp2_common/pico_time_adapter/include",
        "src/rp2_common/pico_unique_id/include",
    };

    for (rp2_common_include_dirs) |dir| {
        lib.addSystemIncludePath(b.path(dir));
    }
}

fn addCompileDefinitions(lib: *std.Build.Step.Compile, chip: Chip, board: []const u8) void {
    lib.root_module.addCMacro("PICO_BUILD", "1");
    lib.root_module.addCMacro("PICO_ON_DEVICE", "1");
    lib.root_module.addCMacro("PICO_NO_HARDWARE", "0");
    lib.root_module.addCMacro("PICO_32BIT", "1");

    // Board definition
    lib.root_module.addCMacro("PICO_BOARD", board);

    switch (chip) {
        .rp2040 => {
            lib.root_module.addCMacro("PICO_RP2040", "1");
            lib.root_module.addCMacro("PICO_RP2350", "0");
        },
        .rp2350 => {
            lib.root_module.addCMacro("PICO_RP2040", "0");
            lib.root_module.addCMacro("PICO_RP2350", "1");
        },
    }

    // SDK version
    lib.root_module.addCMacro("PICO_SDK_VERSION_MAJOR", "2");
    lib.root_module.addCMacro("PICO_SDK_VERSION_MINOR", "2");
    lib.root_module.addCMacro("PICO_SDK_VERSION_REVISION", "0");
    lib.root_module.addCMacro("PICO_SDK_VERSION_STRING", "\"2.2.0\"");
}

// ============================================================================
// Public API for downstream projects
// ============================================================================

/// Returns the appropriate target for a given chip and CPU architecture
pub fn getTarget(chip: Chip, cpu_arch: CpuArch) std.Target.Query {
    return switch (chip) {
        .rp2040 => .{
            .cpu_arch = .thumb,
            .cpu_model = .{ .explicit = &std.Target.arm.cpu.cortex_m0plus },
            .os_tag = .freestanding,
            .abi = .eabi,
        },
        .rp2350 => switch (cpu_arch) {
            .arm => .{
                .cpu_arch = .thumb,
                .cpu_model = .{ .explicit = &std.Target.arm.cpu.cortex_m33 },
                .os_tag = .freestanding,
                .abi = .eabi,
            },
            .riscv => .{
                .cpu_arch = .riscv32,
                .cpu_model = .{ .explicit = &std.Target.riscv.cpu.generic_rv32 },
                .os_tag = .freestanding,
                .abi = .eabi,
            },
        },
    };
}

/// Adds all pico-sdk include paths and compile definitions to a compile step.
/// Call this from your project's build.zig to set up the SDK.
pub fn addTo(sdk_dep: *std.Build.Dependency, compile: *std.Build.Step.Compile, chip: Chip, board: []const u8) void {
    const b = compile.step.owner;

    // Generate config headers for this compile step
    const generated = generateConfigHeadersForDep(b, chip, board);
    compile.addIncludePath(generated);

    // Add libc stubs for freestanding builds (must come before SDK includes)
    compile.addSystemIncludePath(sdk_dep.path("zig/libc_stubs"));

    // Add all SDK include paths
    addSdkIncludePaths(sdk_dep, compile, chip);

    // Add compile definitions
    addSdkCompileDefinitions(compile, chip, board);
}

fn generateConfigHeadersForDep(b: *std.Build, chip: Chip, board: []const u8) std.Build.LazyPath {
    const wf = b.addWriteFiles();

    // Generate pico/version.h
    _ = wf.add("pico/version.h",
        \\/*
        \\ * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
        \\ *
        \\ * SPDX-License-Identifier: BSD-3-Clause
        \\ */
        \\
        \\// THIS FILE IS AUTOGENERATED; DO NOT EDIT
        \\
        \\#ifndef _PICO_VERSION_H
        \\#define _PICO_VERSION_H
        \\
        \\#define PICO_SDK_VERSION_MAJOR    2
        \\#define PICO_SDK_VERSION_MINOR    2
        \\#define PICO_SDK_VERSION_REVISION 0
        \\#define PICO_SDK_VERSION_STRING   "2.2.0"
        \\
        \\#endif
        \\
    );

    // Generate pico_config_extra_headers.h (empty by default)
    _ = wf.add("pico_config_extra_headers.h",
        \\// Extra headers - add custom includes here if needed
        \\
    );

    // Generate pico_config_platform_headers.h based on board and chip
    const platform_header = switch (chip) {
        .rp2040 => b.fmt(
            \\// Platform headers for RP2040
            \\#include "cmsis/rename_exceptions.h"
            \\#include "boards/{s}.h"
            \\
        , .{board}),
        .rp2350 => b.fmt(
            \\// Platform headers for RP2350
            \\#include "cmsis/rename_exceptions.h"
            \\#include "boards/{s}.h"
            \\
        , .{board}),
    };
    _ = wf.add("pico_config_platform_headers.h", platform_header);

    // Generate pico/config_autogen.h
    _ = wf.add("pico/config_autogen.h",
        \\// AUTOGENERATED - DO NOT EDIT
        \\//
        \\// This header includes platform and extra configuration headers.
        \\
        \\// Extra headers (custom user configuration)
        \\#include "pico_config_extra_headers.h"
        \\
        \\// Platform-specific headers (board and chip configuration)
        \\#include "pico_config_platform_headers.h"
        \\
    );

    return wf.getDirectory();
}

fn addSdkIncludePaths(sdk_dep: *std.Build.Dependency, compile: *std.Build.Step.Compile, chip: Chip) void {
    // Common include paths
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_base_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_binary_info/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_bit_ops_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_divider_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_sync/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_time/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_util/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_stdlib_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/pico_usb_reset_interface_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/hardware_claim/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/boot_picobin_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/boot_picoboot_headers/include"));
    compile.addSystemIncludePath(sdk_dep.path("src/common/boot_uf2_headers/include"));

    // Boards
    compile.addSystemIncludePath(sdk_dep.path("src/boards/include"));

    // Chip-specific include paths
    switch (chip) {
        .rp2040 => {
            compile.addSystemIncludePath(sdk_dep.path("src/rp2040/hardware_regs/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2040/hardware_structs/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2040/pico_platform/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2040/boot_stage2/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2_common/cmsis/stub/CMSIS/Device/RP2040/Include"));
        },
        .rp2350 => {
            compile.addSystemIncludePath(sdk_dep.path("src/rp2350/hardware_regs/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2350/hardware_structs/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2350/pico_platform/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2350/boot_stage2/include"));
            compile.addSystemIncludePath(sdk_dep.path("src/rp2_common/cmsis/stub/CMSIS/Device/RP2350/Include"));
        },
    }

    // RP2 common include paths
    const rp2_common_dirs = [_][]const u8{
        "src/rp2_common/boot_bootrom_headers/include",
        "src/rp2_common/cmsis/include",
        "src/rp2_common/cmsis/stub/CMSIS/Core/Include",
        "src/rp2_common/hardware_adc/include",
        "src/rp2_common/hardware_base/include",
        "src/rp2_common/hardware_boot_lock/include",
        "src/rp2_common/hardware_clocks/include",
        "src/rp2_common/hardware_dcp/include",
        "src/rp2_common/hardware_divider/include",
        "src/rp2_common/hardware_dma/include",
        "src/rp2_common/hardware_exception/include",
        "src/rp2_common/hardware_flash/include",
        "src/rp2_common/hardware_gpio/include",
        "src/rp2_common/hardware_hazard3/include",
        "src/rp2_common/hardware_i2c/include",
        "src/rp2_common/hardware_interp/include",
        "src/rp2_common/hardware_irq/include",
        "src/rp2_common/hardware_pio/include",
        "src/rp2_common/hardware_pll/include",
        "src/rp2_common/hardware_powman/include",
        "src/rp2_common/hardware_pwm/include",
        "src/rp2_common/hardware_rcp/include",
        "src/rp2_common/hardware_resets/include",
        "src/rp2_common/hardware_riscv/include",
        "src/rp2_common/hardware_riscv_platform_timer/include",
        "src/rp2_common/hardware_rtc/include",
        "src/rp2_common/hardware_sha256/include",
        "src/rp2_common/hardware_spi/include",
        "src/rp2_common/hardware_sync/include",
        "src/rp2_common/hardware_sync_spin_lock/include",
        "src/rp2_common/hardware_ticks/include",
        "src/rp2_common/hardware_timer/include",
        "src/rp2_common/hardware_uart/include",
        "src/rp2_common/hardware_vreg/include",
        "src/rp2_common/hardware_watchdog/include",
        "src/rp2_common/hardware_xip_cache/include",
        "src/rp2_common/hardware_xosc/include",
        "src/rp2_common/pico_aon_timer/include",
        "src/rp2_common/pico_async_context/include",
        "src/rp2_common/pico_atomic/include",
        "src/rp2_common/pico_bit_ops/include",
        "src/rp2_common/pico_bootrom/include",
        "src/rp2_common/pico_clib_interface/include",
        "src/rp2_common/pico_crt0/include",
        "src/rp2_common/pico_divider/include",
        "src/rp2_common/pico_double/include",
        "src/rp2_common/pico_flash/include",
        "src/rp2_common/pico_float/include",
        "src/rp2_common/pico_i2c_slave/include",
        "src/rp2_common/pico_int64_ops/include",
        "src/rp2_common/pico_malloc/include",
        "src/rp2_common/pico_mem_ops/include",
        "src/rp2_common/pico_multicore/include",
        "src/rp2_common/pico_platform_common/include",
        "src/rp2_common/pico_platform_compiler/include",
        "src/rp2_common/pico_platform_panic/include",
        "src/rp2_common/pico_platform_sections/include",
        "src/rp2_common/pico_printf/include",
        "src/rp2_common/pico_rand/include",
        "src/rp2_common/pico_runtime/include",
        "src/rp2_common/pico_runtime_init/include",
        "src/rp2_common/pico_sha256/include",
        "src/rp2_common/pico_standard_binary_info/include",
        "src/rp2_common/pico_standard_link/include",
        "src/rp2_common/pico_stdio/include",
        "src/rp2_common/pico_stdio_semihosting/include",
        "src/rp2_common/pico_stdio_uart/include",
        "src/rp2_common/pico_stdio_usb/include",
        "src/rp2_common/pico_stdlib/include",
        "src/rp2_common/pico_time_adapter/include",
        "src/rp2_common/pico_unique_id/include",
    };

    for (rp2_common_dirs) |dir| {
        compile.addSystemIncludePath(sdk_dep.path(dir));
    }
}

fn addSdkCompileDefinitions(compile: *std.Build.Step.Compile, chip: Chip, board: []const u8) void {
    compile.root_module.addCMacro("PICO_BUILD", "1");
    compile.root_module.addCMacro("PICO_ON_DEVICE", "1");
    compile.root_module.addCMacro("PICO_NO_HARDWARE", "0");
    compile.root_module.addCMacro("PICO_32BIT", "1");
    compile.root_module.addCMacro("PICO_BOARD", board);

    switch (chip) {
        .rp2040 => {
            compile.root_module.addCMacro("PICO_RP2040", "1");
            compile.root_module.addCMacro("PICO_RP2350", "0");
        },
        .rp2350 => {
            compile.root_module.addCMacro("PICO_RP2040", "0");
            compile.root_module.addCMacro("PICO_RP2350", "1");
        },
    }

    compile.root_module.addCMacro("PICO_SDK_VERSION_MAJOR", "2");
    compile.root_module.addCMacro("PICO_SDK_VERSION_MINOR", "2");
    compile.root_module.addCMacro("PICO_SDK_VERSION_REVISION", "0");
    compile.root_module.addCMacro("PICO_SDK_VERSION_STRING", "\"2.2.0\"");
}

/// Add SDK C source files to a compile step
/// This allows you to selectively include SDK sources you need
pub fn addCSourceFiles(
    sdk_dep: *std.Build.Dependency,
    compile: *std.Build.Step.Compile,
    sources: []const []const u8,
) void {
    for (sources) |src| {
        compile.addCSourceFile(.{
            .file = sdk_dep.path(src),
            .flags = sdk_c_flags,
        });
    }
}

const sdk_c_flags: []const []const u8 = &.{
    "-std=c11",
    "-ffunction-sections",
    "-fdata-sections",
    "-fno-strict-aliasing",
    "-ffreestanding",
    "-D__always_inline=__attribute__((__always_inline__)) inline",
    "-D__printflike(a,b)=__attribute__((__format__(__printf__,a,b)))",
    "-Dstatic_assert=_Static_assert",
};

/// SDK components that can be added to a project
pub const Component = enum {
    hardware_gpio,
    hardware_clocks,
    hardware_pll,
    hardware_xosc,
    hardware_watchdog,
    hardware_irq,
    hardware_sync,
    hardware_timer,
    hardware_ticks,
    hardware_uart,
    hardware_spi,
    hardware_i2c,
    hardware_pwm,
    hardware_adc,
    hardware_dma,
    hardware_pio,
    hardware_flash,
    pico_platform,
    pico_runtime,
};

/// Add SDK components to a compile step. This is the recommended way to use the SDK.
/// Components automatically include their dependencies.
pub fn addComponent(
    sdk_dep: *std.Build.Dependency,
    compile: *std.Build.Step.Compile,
    chip: Chip,
    component: Component,
) void {
    const sources = getComponentSources(chip, component);
    for (sources) |src| {
        compile.addCSourceFile(.{
            .file = sdk_dep.path(src),
            .flags = sdk_c_flags,
        });
    }
}

/// Add multiple SDK components at once
pub fn addComponents(
    sdk_dep: *std.Build.Dependency,
    compile: *std.Build.Step.Compile,
    chip: Chip,
    components: []const Component,
) void {
    for (components) |component| {
        addComponent(sdk_dep, compile, chip, component);
    }
}

fn getComponentSources(chip: Chip, component: Component) []const []const u8 {
    return switch (component) {
        .hardware_gpio => switch (chip) {
            .rp2040 => &.{
                "src/rp2_common/hardware_gpio/gpio.c",
            },
            .rp2350 => &.{
                "src/rp2_common/hardware_gpio/gpio.c",
                "zig/gpio_coproc_wrappers.c",
            },
        },
        .hardware_clocks => &.{
            "src/rp2_common/hardware_clocks/clocks.c",
        },
        .hardware_pll => &.{
            "src/rp2_common/hardware_pll/pll.c",
        },
        .hardware_xosc => &.{
            "src/rp2_common/hardware_xosc/xosc.c",
        },
        .hardware_watchdog => &.{
            "src/rp2_common/hardware_watchdog/watchdog.c",
        },
        .hardware_irq => &.{
            "src/rp2_common/hardware_irq/irq.c",
        },
        .hardware_sync => switch (chip) {
            .rp2040 => &.{
                "src/rp2_common/hardware_sync/sync.c",
            },
            .rp2350 => &.{
                "src/rp2_common/hardware_sync/sync.c",
                "src/rp2_common/hardware_sync_spin_lock/sync_spin_lock.c",
            },
        },
        .hardware_timer => &.{
            "src/rp2_common/hardware_timer/timer.c",
        },
        .hardware_ticks => &.{
            "src/rp2_common/hardware_ticks/ticks.c",
        },
        .hardware_uart => &.{
            "src/rp2_common/hardware_uart/uart.c",
        },
        .hardware_spi => &.{
            "src/rp2_common/hardware_spi/spi.c",
        },
        .hardware_i2c => &.{
            "src/rp2_common/hardware_i2c/i2c.c",
        },
        .hardware_pwm => &.{}, // Header-only component
        .hardware_adc => &.{
            "src/rp2_common/hardware_adc/adc.c",
        },
        .hardware_dma => &.{
            "src/rp2_common/hardware_dma/dma.c",
        },
        .hardware_pio => &.{
            "src/rp2_common/hardware_pio/pio.c",
        },
        .hardware_flash => &.{
            "src/rp2_common/hardware_flash/flash.c",
        },
        .pico_platform => switch (chip) {
            .rp2040 => &.{
                "src/rp2040/pico_platform/platform.c",
                "src/rp2_common/pico_platform_common/common.c",
                "src/rp2_common/pico_platform_panic/panic.c",
                "zig/platform_wrappers.c",
            },
            .rp2350 => &.{
                "src/rp2350/pico_platform/platform.c",
                "src/rp2_common/pico_platform_common/common.c",
                "src/rp2_common/pico_platform_panic/panic.c",
                "zig/platform_wrappers.c",
            },
        },
        .pico_runtime => &.{
            "src/common/hardware_claim/claim.c",
        },
    };
}
